openapi: 3.0.0

info:
  title: Api Definitions
  description: Only for Api
  version: 0.1.0

paths:
  /api/designs/{category}:
    get:
      summary: Designs
      parameters:
        - in: path
          name: category
          schema:
            type: integer
            enum: [1, 2]
          required: true
      responses:
        '200':
          description: succeed
          content:
            application/json:
              schema:
                type: object
                properties:
                  designs:
                    type: array
                    items:
                      $ref: '#/components/schemas/Design'
                required:
                  - designs

  /api/designer:
    get:
      summary: Designer
      responses:
        '200':
          description: succeed
          content:
            application/json:
              schema:
                type: object
                properties:
                  designer:
                    $ref: '#/components/schemas/Designer'
                required:
                  - designer

components:
  schemas:
    Design:
      properties:
        _id:
          type: string
        titleHeading:
          type: string
        title:
          type: string
        descriptionHeading:
          type: string
        description:
          type: string
        file:
          type: string
        category:
          type: number
        baseColor:
          type: string
      required:
        - _id
        - titleHeading
        - title
        - descriptionHeading
        - description
        - file
        - category
        - baseColor
    Designer:
      properties:
        _id:
          type: string
        name:
          type: string
        email:
          type: string
        descriptionHeading:
          type: string
        description:
          type: string
        file:
          type: string
        baseColor:
          type: string
      required:
        - _id
        - name
        - email
        - descriptionHeading
        - description
        - file
        - baseColor
