/**
 * Api Definitions
 * Only for Api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Design {
    'id'?: string;
    'titleHeading': string;
    'title': string;
    'descriptionHeading': string;
    'description': string;
    'file': string;
    'category': number;
    'baseColor': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "_id",
            "type": "string"
        },
        {
            "name": "titleHeading",
            "baseName": "titleHeading",
            "type": "string"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "descriptionHeading",
            "baseName": "descriptionHeading",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "file",
            "baseName": "file",
            "type": "string"
        },
        {
            "name": "category",
            "baseName": "category",
            "type": "number"
        },
        {
            "name": "baseColor",
            "baseName": "baseColor",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Design.attributeTypeMap;
    }
}

